### ISSUE TITLE
OrderBy methods are commented out?

### ISSUE THREAD

**Issue by rekosko** [ubergeoff/HollowPoint.Azure#2]
Hi,

Just a quick question. Why those methods responsible for ordering are disabled?

https://github.com/ubergeoff/HollowPoint.Azure/blob/5295595018044c7b2154161b2903faf175a518a4/HollowPoint.Azure/HollowPoint.Azure/Tools/ODataTranslator.cs#L98

**Comment by ubergeoff** [comment]
Don't recall. Sorry. Been a long time since I wrote that... 
Probably did not have time to test that...
